### ISSUE TITLE
Hang when run yarn install 

### ISSUE THREAD

**Issue by iShawnWang** [nodejs/node-report#107]
<img width="696" alt="2018-01-12 2 39 20" src="https://user-images.githubusercontent.com/20266594/34841049-e45a4f5e-f741-11e7-9e14-be77a2f22434.png">

It hang for 10 min, on Ubuntu 16.04
Is that lack of some native package ? Such as `libstdc`, `libuv ` ?

**Comment by sam-github** [comment]
Probably better reported as a bug to the yarn project.

**Comment by iShawnWang** [comment]
I think maybe `node-report` have some native reference, and can't be fulfilled on Linux ?

**Comment by cjihrig** [comment]
Does installing with `npm` work?

**Comment by sam-github** [comment]
node-report is developed and tested on Linux, if it can't install with npm its likely an interaction with your system, if it can install with npm but not with yarn, its most likely a yarn incompatibility with npm.

**Comment by iShawnWang** [comment]
<img width="1391" alt="2018-01-19 10 57 49" src="https://user-images.githubusercontent.com/20266594/35132749-b16b086a-fd07-11e7-8da0-cbf9ebc526c7.png">

<img width="1391" alt="2018-01-19 10 58 00" src="https://user-images.githubusercontent.com/20266594/35132755-b75f0cbc-fd07-11e7-8cdf-72317d786fdc.png">

**Comment by iShawnWang** [comment]
OMG, what's going on here, I am using Ubuntu 16.04 and somehow `npm install node-report` drain my CPU and memory.

I remember that I face the similar problem when installing a webpack plugin which helps me to optimize image size when webpack build.

Any idea why this happens? Is that my 1GB memory is not enough of my Ali Cloud Server ?

**Comment by iShawnWang** [comment]
But it works and emit success when i run `node-gyp rebuild` ~

**Comment by richardlau** [comment]
There was an infinite loop bug in `node-gyp` (https://github.com/nodejs/node-gyp/pull/1384) that was fixed in `node-gyp` 3.7.0 which is a potential cause of high CPU/memory usage.
