### ISSUE TITLE
Add prebuilt binaries

### ISSUE THREAD

**Issue by jt-nti** [nodejs/node-report#109]
This came up in discussions on issue #103

I'm particularly interested from a Windows platform point of view in relation to expanding Hyperledger Composer platform support hyperledger/composer#65 - it would be great to be able to easily get node-report installed on Windows machines, which aren't typically set up for compilation.

**Comment by mhdawson** [comment]
At the diagnostic summit, the consensus was to pull node-report into core.  I think that will be even better.  We just need to get started on that.

**Comment by jt-nti** [comment]
It would definitely be good to get node-report into core! Is there any likelihood of adding prebuilt binaries for existing node versions, even if it's only on Windows where getting set up for compilation appears to be more of a barrier?
