### ISSUE TITLE
Error when installing npm install -g composer-cli

### ISSUE THREAD

**Issue by DevenSuji** [nodejs/node-report#111]
xxxxxxxx@ubuntu:~$ sudo npm install -g composer-cli

WARN engine composer-cli@0.19.5: wanted: {"node":">=8","npm":">=5"} (current: {"node":"4.2.6","npm":"3.5.2"})
loadDep:yargs → resolveWi 
loadDep:yargs → resolveWi 
loadDep:yargs → get 
loadDep:yargs → resolveWi
loadDep:yargs → resolveWi 
loadDep:yargs → resolveWi 
loadDep:composer-connecto 
loadDep:punycode → 304
loadDep:temp → 304
loadDep:temp → resolveWit 
loadDep:tar-stream → cach 
loadDep:request → mapToRe
/usr/local/bin/composer -> /usr/local/lib/node_modules/composer-cli/cli.js

> dtrace-provider@0.8.6 install /usr/local/lib/node_modules/composer-cli/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

/usr/bin/env: ‘node’: No such file or directory
sh: 1: node: not found
npm WARN install:dtrace-provider@0.8.6 dtrace-provider@0.8.6 install: `node-gyp rebuild || node suppress-error.js`
npm WARN install:dtrace-provider@0.8.6 spawn ENOENT

> node-report@2.2.1 install /usr/local/lib/node_modules/composer-cli/node_modules/node-report
> node-gyp rebuild

/usr/bin/env: ‘node’: No such file or directory
/usr/local/lib
└── (empty)

npm WARN optional Skipping failed optional dependency /composer-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm ERR! Linux 4.13.0-43-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "composer-cli"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-report@2.2.1 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-report@2.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-report package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-report
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-report
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xxxxxxxx/npm-debug.log
npm ERR! code 1

**Comment by mhdawson** [comment]
@richardlau can you take a look at this one.

**Comment by richardlau** [comment]
> /usr/bin/env: ‘node’: No such file or directory
sh: 1: node: not found

@DevenSuji Do you have node installed and on your PATH? In theory node-report should be compatible with Node.js 4, but please note that Node.js 4 is EOL and you really should plan to move to either Node.js 6, 8 or 10. 

> WARN engine composer-cli@0.19.5: wanted: {"node":">=8","npm":">=5"} (current: {"node":"4.2.6","npm":"3.5.2"})

Also suggests that composer-cli wants at least Node.js 8.

**Comment by MuffinMan82** [comment]
nothing??? I am having the same issue.

**Comment by mhdawson** [comment]
@richardlau are you going to be able to chime in?

**Comment by Paul-dH** [comment]
I have the same issue:
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /glob-watcher/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /nunjucks/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
```

Node is on my path.

**Comment by richardlau** [comment]
@Paul-dH Those warnings are nothing to do with node-report.

**Comment by Paul-dH** [comment]
Hi @richardlau,

I think you're correct, after a search I found this:
Link: [stackoverflow](https://stackoverflow.com/questions/50548574/fsevents-optional-dependency-returns-not-compatible-with-system)

This means that this warning will pop-up on all systems, OSX excluded.

**Comment by singh-amarjeet** [comment]
I am using node v8.9.0 and npm v5.5.1 and still getting error:

user@gaurav-toora-XL-01:~$ npm install -g composer-playground@0.20
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
/home/user/.nvm/versions/node/v8.9.0/bin/composer-playground -> /home/user/.nvm/versions/node/v8.9.0/lib/node_modules/composer-playground/cli.js

> dtrace-provider@0.8.7 install /home/user/.nvm/versions/node/v8.9.0/lib/node_modules/composer-playground/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/user/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/user/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/user/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/user/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/user/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/user/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.4.0-141-generic
gyp ERR! command "/home/user/.nvm/versions/node/v8.9.0/bin/node" "/home/user/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/.nvm/versions/node/v8.9.0/lib/node_modules/composer-playground/node_modules/dtrace-provider
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

> pkcs11js@1.0.17 install /home/user/.nvm/versions/node/v8.9.0/lib/node_modules/composer-playground/node_modules/pkcs11js
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/user/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/user/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/user/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/user/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/user/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/user/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.4.0-141-generic
gyp ERR! command "/home/user/.nvm/versions/node/v8.9.0/bin/node" "/home/user/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/.nvm/versions/node/v8.9.0/lib/node_modules/composer-playground/node_modules/pkcs11js
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pkcs11js@1.0.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pkcs11js@1.0.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-03-05T09_02_17_005Z-debug.log

**Comment by richardlau** [comment]
> gyp ERR! build error
> gyp ERR! stack Error: not found: make

@singh-amarjeet You need to have `make` installed (see prerequisites of `node-gyp`: https://github.com/nodejs/node-gyp#on-unix). Nothing in your log refers to `node-report`.
