### ISSUE TITLE
dist folder not in perishable-network

### ISSUE THREAD

**Issue by sule272005** [nodejs/node-report#115]
Please see below excerpts of error I ran into after I tried to nom install so as to get access to the dist/ folder;

S-MacBook-Pro:perishable-network si$ npm install

> node-report@2.2.1 install /Users/si/perishable-network/node_modules/node-report
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/anaconda3/bin/python" is v3.6.5, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Users/si/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Users/si/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:189:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:351:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:497:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/si/.nvm/versions/node/v6.11.3/bin/node" "/Users/si/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/si/perishable-network/node_modules/node-report
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
perishable-network@0.2.6 /Users/si/perishable-network
└── (empty)

npm ERR! Darwin 17.7.0
npm ERR! argv "/Users/si/.nvm/versions/node/v6.11.3/bin/node" "/Users/si/.nvm/versions/node/v6.11.3/bin/npm" "install"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-report@2.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-report@2.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-report package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-report
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-report
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/si/perishable-network/npm-debug.log
npm ERR! code 1

HOW CAN I RESOLVE THIS?

**Comment by mhdawson** [comment]
Form this 

```
gyp ERR! stack Error: Python executable "/anaconda3/bin/python" is v3.6.5, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack at failPythonVersion 
```

I think you need to have/use a version of Python that it recommends.  This is not specific to node-report but I think any native module.

**Comment by sule272005** [comment]
Thank you, error resolved
