### ISSUE TITLE
No backtrace on IBM i

### ISSUE THREAD

**Issue by ThePrez** [nodejs/node-report#121]
I have some code changes nearly ready to commit for backtrace support on IBM i. I'm opening this issue to document the current shortcoming but also for advice on the best way for me to contribute, based on the great progress with moving node-report into core (#110) 
Any guidance is appreciated. Thank you!

**Comment by richardlau** [comment]
It depends on how quickly you want the functionality available. The fastest way to get the functionality to users would be to PR here (we can release a new version of the module that can be installed via your package manager of choice on the existing Node.js releases).

**Comment by mhdawson** [comment]
I think both may make sense.  For 8.x and 10.x it might be a while (if ever) that node-report could be backported so improving support there makes sense.  

On the other hand once the PR lands in Node core that is where much of the focus will be so you want to land the changes there as well.
