### ISSUE TITLE
node-report reports error thrown via napi as uncaught when in fact the JS caller catches it

### ISSUE THREAD

**Issue by ghost** [nodejs/node-report#131]
* **Node.js Version**: 10.15.3
* **OS**: Windows 10 x64
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: node-report 2.2.7

node-report incorrectly reports an uncaught exception for an error that is in fact caught *if the error is thrown in native code using napi_throw.*

I am filing this issue here since I know that node-report is being pulled into node. I don't know if the issue exists in node v12. I have not tried it. 

Here is how to reproduce the problem in v10 using the node-report npm module:

```js
const nodereport = require("node-report/api");
nodereport.setEvents("exception+fatalerror+apicall");
nodereport.setDirectory("d:\\crash");
nodereport.setVerbose("yes");
try {
    nativeFunctionThatThrows();
} catch (err) {
    console.log("got here");
}
```
The function `nativeFunctionThatThrows` is implemented in my node addon. It calls `napi_throw`. 

The output is:
```
Writing Node.js report to file: node-report.20190621.145907.22080.001.txt
Node.js report completed
got here
```
A portion of the generated node-report is:

```
Event: exception, location: "OnUncaughtException".
[snip]
==== Native Stack Trace ========================================================

 0: [pc=0x00007FF8E6961FE0] nodereport::TriggerNodeReport [+0] in d:\imjs\imodeljs\common\temp\node_modules\.registry.npmjs.org\node-report\2.2.7\node_modules\node-report\src\node_report.cc: line: 196
 1: [pc=0x00007FF8E6969AB0] nodereport::OnUncaughtException [+0] in d:\imjs\imodeljs\common\temp\node_modules\.registry.npmjs.org\node-report\2.2.7\node_modules\node-report\src\module.cc: line: 184
 2: [pc=0x00007FF7E97F3E10] v8::internal::Isolate::PrintStack [+5398]
 3: [pc=0x00007FF7E9328200] v8::Isolate::ThrowException [+62]
 4: [pc=0x00007FF7E90718F0] napi_throw [+187]
 5: [pc=0x00007FF8E82FBB19]
```

The node uncaughtException event has no such problem. When I change the example above to this:
```js
process.on("uncaughtException", (err, origin) => {
    console.error(err);
    console.log(origin);
});
try {
    nativeFunctionThatThrows();
} catch (err) {
    console.log("got here");
}
```
The output is simply `got here`.

**Comment by hashseed** [comment]
Can you maybe construct a V8 cctest for this case?
