### ISSUE TITLE
Backport of new features added to core

### ISSUE THREAD

**Issue by mmarchini** [nodejs/node-report#132]
Are there any plans on backporting the features that were added to core into this module (like the JSON format)?

**Comment by richardlau** [comment]
> 
> 
> Are there any plans on backporting the features that were added to core into this module (like the JSON format)?

There are no plans that I am aware of. If you have specific requirements they can be considered. The core implementation has diverged from this repository quite a bit as it has access to core internals that this module does not.

The JSON format would probably be quite a bit of work and, if can't be made optional, semver-major.

Pull requests are always welcome. As are existing org collaborators who wish to become collaborators in this repository 😄.
