### ISSUE TITLE
node-report: sunsetting the module, archiving the repo

### ISSUE THREAD

**Issue by gireeshpunathil** [nodejs/node-report#142]
diagnostic report is now stable in the master: https://github.com/nodejs/node/pull/32242 , hopefully will make it into node.js v14 next month. The only known bug is being worked out too.

This issue is to identify and discuss any other pre-requisites or conditions that need to be met for this repo to be archived and the `npm` module to be sunset, derive at a consensus.

**Comment by richardlau** [comment]
I don't believe diagnostic report has been or will be backported to Node.js 10 so we shouldn't archive this repository until Node.js 10 goes End-of-Life.

**Comment by richardlau** [comment]
Node.js 10 is now End-of-Life and all currently supported versions of Node.js (i.e. 12, 14 and 16) contain the built in diagnostics report feature. So I propose:
- [ ] Deprecating the package on the npm registry. I propose setting a deprecation message of
```
This module has been superseded by the diagnostics report feature of Node.js core. It is now unmaintained.
```
- [ ] Removing the [nodereport-continuous-integration-latest](https://ci.nodejs.org/view/post-mortem/job/nodereport-continuous-integration-latest/) and [test-nodereport](https://ci.nodejs.org/view/post-mortem/job/test-nodereport/) CI jobs.
- [ ] Open an issue in https://github.com/nodejs/admin requesting this repository be archived.

I'll wait until the end of this week in case there are any objections/comments on the deprecation wording.
cc @nodejs/diagnostics

**Comment by richardlau** [comment]
Opened https://github.com/nodejs/admin/issues/621 to request that this repository be archived.
