### ISSUE TITLE
I'm trying to Installing the development environment https://hyperledger.github.io/composer/v0.19/installing/development-tools.html ,  using this code  npm install -g composer-cli@0.19 but this msg shown to me 

### ISSUE THREAD

**Issue by stu1069710** [nodejs/node-report#143]
I'm trying to Installing the development environment https://hyperledger.github.io/composer/v0.19/installing/development-tools.html ,  using this code 
npm install -g composer-cli@0.19
but this msg shown to me 

npm WARN notsup Not compatible with your version of node/npm: fabric-client@1.2.1
npm WARN almed@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! node-report@2.2.1 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-report@2.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/User/.npm/_logs/2020-03-23T12_02_11_549Z-debug.log

please help me

**Comment by richardlau** [comment]
Hyperledger Composer is deprecated (see https://github.com/hyperledger/composer/blob/master/README.md) with a recommendation to use [Hyperledger Fabric](https://hyperledger-fabric.readthedocs.io) instead.

Hyperledger Composer's composer-cli is hardcoded to use an old outdated version of node-report: https://github.com/hyperledger/composer/blob/06ac7a75090eb552752b9c0526b9dabb7a69f65d/packages/composer-cli/package.json#L57
