### ISSUE TITLE
Rename primary branch to main

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-report#148]
We are going through all of the node.js repositories to rename the primary branch to main. Please see nodejs/node#33864 for more context.

 I don't think there should be issues with the rename.

Please let me know if there are any concerns otherwise I'll look to do the rename Friday May 4th.

**Comment by richardlau** [comment]
CI for node-report in on Jenkins (https://ci.nodejs.org/view/post-mortem/). There are some references to `master` in the job config -- @mhdawson do you know if GitHub forwards cli `git` requests for `master` to `main`?

Now that Node.js 10 is End-of-Life we should probably deprecate this module and archive this repository anyway as per https://github.com/nodejs/node-report/issues/142 as all in-support versions of Node.js have built in diagnostics report available.

**Comment by mhdawson** [comment]
>  cli git requests for master to main

Not sure, but I agree that we should just deprecate and disabling the CI would likely be the first step anyway.

**Comment by mhdawson** [comment]
@richardlau I saw you deprecated, is the CI disabled so I can do the change?

**Comment by richardlau** [comment]
@mhdawson Yes, CI has been disabled (actually removed). Go ahead a do the change.

**Comment by mhdawson** [comment]
renamed, closing
