### ISSUE TITLE
add backup npm owners

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/node-report#21]
We'll have an npm org soon I think, see https://github.com/nodejs/CTC/issues/26, but would still be good in the mean time.

**Comment by rnchamberlain** [comment]
+1. This repo is owned by https://github.com/orgs/nodejs/teams/post-mortem which currently has 13 members - I believe they all have the power to push/merge. In advance of the npm org thing I guess we just need to add some folks to the npm using this button on https://www.npmjs.com/package/nodereport:

![capture](https://cloud.githubusercontent.com/assets/16722535/20357349/85b8d52e-ac1f-11e6-8e47-96280863ac80.JPG)

**Comment by rnchamberlain** [comment]
Added @mhdawson as backup npm owner

**Comment by richardlau** [comment]
Also https://github.com/nodejs/TSC/issues/211

**Comment by rnchamberlain** [comment]
See https://github.com/nodejs/build/pull/670

**Comment by rnchamberlain** [comment]
We now have https://www.npmjs.org/~nodejs-foundation as backup owner on https://www.npmjs.org/package/node-report, so closing this.
