### ISSUE TITLE
nit? s/nodereport/node-report

### ISSUE THREAD

**Issue by joshgav** [nodejs/node-report#35]
I think `node-report` is closer to our typical conventions than `nodereport`, plus it fits nicely with node-inspect, node-heapdump, node-profiler etc. Do you think it would be worth changing the name of the repo, module, etc.? Certainly the sooner the better if we're going to do that.

Personally I think we should change it, I can even put it on my own backlog if others agree.

**Comment by gibfahn** [comment]
I think if we're going to change it the earlier the better.

**Comment by richardlau** [comment]
https://www.npmjs.com/package/node-report Is already taken.

**Comment by chirag04** [comment]
i'm not using `node-report` and seems like nobody else is. i don't even remember if node-report is actually doing anything meaningful.

happy to transfer.

**Comment by rnchamberlain** [comment]
Thanks @chirag04, node-report would be a better name for this project and module

**Comment by mhdawson** [comment]
Provided we can get the name in the appropriate places +1 from me.

**Comment by chirag04** [comment]
I added @rnchamberlain as the owner. Feel to claim it. let me know if i can do anything else to help here.

**Comment by richardlau** [comment]
We're due a semver-major bump for #25 -- Would seem the ideal time to do the rename (if it's not going to take long).

**Comment by rnchamberlain** [comment]
@richardlau agree re https://github.com/nodejs/nodereport/issues/25, but I also have a fix coming up for https://github.com/nodejs/nodereport/issues/6 which changes nodereport behaviour and I'd like to release that at the same time. 

Currently nodereport is at v1.0.7 and node-report is v0.1.0. Would we move node-report to v1.0.0?

**Comment by gibfahn** [comment]
@rnchamberlain It's probably worth creating a github milestone for the next major release.

+1 to `v2.0.0`

**Comment by richardlau** [comment]
#37 handles renaming in the source code. 

Who can rename this repository?

**Comment by rnchamberlain** [comment]
According to https://help.github.com/articles/renaming-a-repository/ someone with the powers will have a gear wheel/settings tab showing on the main repo page https://github.com/nodejs/nodereport. I'm not seeing that myself.

**Comment by williamkapke** [comment]
Looking at the list of Org `owners` that have also been somewhat involved in this group... let's ping @mhdawson and maybe @Fishrock123

**Comment by rnchamberlain** [comment]
Suggested steps required, in sequence:

1. Rename this repo to github.com/nodejs/node-report

2. Update the module code, readme, tests and demos to use the new "node-report" name where appropriate. I don't think the global edit approach in https://github.com/nodejs/nodereport/pull/37 works, we need to start over on that change. 

3. Version as v2.0.0 and release on https://www.npmjs.com/package/node-report

4. Update the readme on https://www.npmjs.com/package/nodereport to say it's obsolete, and reference the new one. For npm to publish the updated readme we'll need a package.json increment to v1.0.8 on there.

Note: currently the report files produced are named NodeReport.&lt;date&gt;.&lt;time&gt;.&lt;pid&gt;.&lt;seq&gt;.txt. I think we should change that to node-report.&lt;date&gt;.&lt;time&gt;.&lt;pid&gt;.&lt;seq&gt;.txt

**Comment by rnchamberlain** [comment]
node-report v2.0.0 now published on https://www.npmjs.com/package/node-report

for changes see https://github.com/nodejs/node-report/blob/master/CHANGES.md

**Comment by rnchamberlain** [comment]
All done now I think, new git repo is https://github.com/nodejs/node-report, new package is https://www.npmjs.com/package/node-report. 

Added message in old package README and npm deprecate warning on nodereport.
