### ISSUE TITLE
Allowing user to access report content directly rather than reading back from the file.

### ISSUE THREAD

**Issue by hhellyer** [nodejs/node-report#39]
We've had a feature request to allow users of the nodereport api to get the content of the nodereport file directly rather than having to read it back in from the file. This would make it easier to embed nodereport in other tools.

I'm going to take a look at this but up front I can think of some important limitations:
 - This will only work on API calls. We can't send the content of nodereport to a  callback on a fatal error. (At that point Node.js isn't available for use.)
 
 - We will have to return all the content in one go, synchronously. If we stream it  back bit by bit to a callback then code is running and changing the state of Node.js while  we try and report it's state. The response from nodereport is a snapshot of a point in time.

 I'm going to do some more investigation but any other feedback into the design would be welcome.

**Comment by rnchamberlain** [comment]
Maybe a separate issue, but some work is needed on the error handling for the API use-case. If a nodereport is triggered via the API, we should probably use Nan::ThrowError() rather than writing messages to stderr.

**Comment by mhdawson** [comment]
Agreed that we can't have the state changing as we generate the report so it does need to be a one shot generation.    

Assuming we have to generate in full, then we'll need a string which is the full size of the nodereport.  However having that we could still provide a streaming api that returns the content of that string, but that might just lead to needing even more memory.

May just make sense to have a method that returns the full node report and then a second one that is called to free the corresponding buffer.

**Comment by rnchamberlain** [comment]
Delivered in npm https://www.npmjs.com/package/node-report v2.1.0

**Comment by hhellyer** [comment]
This has been released in v2.1.0 - closing issue.
