### ISSUE TITLE
Node-report tests hanging in CI

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-report#49]
Working to setup this job: https://ci.nodejs.org/view/post-mortem/job/nodereport-continuous-integration/

but the job seems to just hang:
```bash
iojs@test-digitalocean-ubuntu14-x64-1:~/build/workspace/nodereport-continuous-integration/MACHINE/ubuntu1404-64$ node /home/iojs/build/workspace/nodereport-continuous-integration/MACHINE/ubuntu1404-64/node-v8.0.0-nightly20170131aa8eb8747c-linux-x64/bin/citgm https://github.com/nodejs/node-report.git
info:    starting            | https://github.com/nodejs/node-report.git
info:    lookup              | 9b36120a7b4a11336b6b71ae0d7237e837878a2a
info:    lookup-notfound     | 9b36120a7b4a11336b6b71ae0d7237e837878a2a
info:    9b36120a7b4a11336b6b71ae0d7237e837878a2a npm:| Downloading project: https://github.com/nodejs/node-report.git
info:    9b36120a7b4a11336b6b71ae0d7237e837878a2a npm:| Project downloaded nodereport-1.0.7.tgz
info:    9b36120a7b4a11336b6b71ae0d7237e837878a2a npm:| npm install started
info:    9b36120a7b4a11336b6b71ae0d7237e837878a2a npm:| npm install successfully completed
info:    9b36120a7b4a11336b6b71ae0d7237e837878a2a npm:| test suite started
```

**Comment by mhdawson** [comment]
When I install on the same machine and run I get

```bash
iojs@test-digitalocean-ubuntu14-x64-1:~/build/workspace/nodereport-continuous-integration/MACHINE/ubuntu1404-64/node_modules/nodereport$ npm test

> nodereport@1.0.7 test /home/iojs/build/workspace/nodereport-continuous-integration/MACHINE/ubuntu1404-64/node_modules/nodereport
> tap test/test*.js

Reading TAP data from stdin (use "-" argument to suppress)
```

Which also looks like it just hangs there waiting. 

@hhellyer I assume you have run the tests locally is there something I'm missing here ?   I expect that citgm expects to just be able to run using npm test.

**Comment by richardlau** [comment]
> `Reading TAP data from stdin (use "-" argument to suppress)`

@mhdawson This usually means that the `tap` plugin has failed to find any tests and falls back to reading from stdin. Does your local installation have a `test` dir?

Cc @gadams

**Comment by gibfahn** [comment]
>Cc @gadams

I think you meant @gdams

**Comment by richardlau** [comment]
> I think you meant @gdams
I did indeed.

**Comment by gdams** [comment]
@richardlau @mhdawson you need to use `citgm https://github.com/nodejs/node-report/archive/master.tar.gz` to include the tests.

**Comment by gdams** [comment]
@mhdawson also do you really want to be relying on citgm for your CI job? would't it make more sense to:
`npm install nodereport`
`cd node_modules/nodereport`
`npm install`
`npm test`

**Comment by mhdawson** [comment]
Ok talked to George, believe I understand what I was doing wrong.  Closing.
