### ISSUE TITLE
Add sample node-report output in README.md or 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-report#51]
I think it would be useful to include sample node-report output in the README.md or linked to it so that people can more easily grasp the information you can get and how easy it is to read. 

What do you think ?

**Comment by richardlau** [comment]
I'm in favour with the caveat that the output can be quite long so if it is inlined into the README.md (as opposed to linked) maybe some editing (e.g. probably don't need to list all the environment variables)?

**Comment by gibfahn** [comment]
+1 to having a cut-down sample output

**Comment by rnchamberlain** [comment]
Suggest add 4 samples for the OOM, exception, signal and API use-cases into the project wiki https://github.com/nodejs/node-report/wiki then link from the README.
