### ISSUE TITLE
Create a collaborator guide

### ISSUE THREAD

**Issue by gibfahn** [nodejs/node-report#65]
Now that the CI is working for node-report (see https://github.com/nodejs/node-report/issues/18#issuecomment-283640701), we should document how to run CI for collaborators, maybe a COLLABORATOR_GUIDE.md (we could take inspiration from [the node core versions](https://github.com/nodejs/node/blob/master/COLLABORATOR_GUIDE.md)).

**Comment by rnchamberlain** [comment]
Agree. We have a CONTRIBUTING.md already, can we add it to that?

**Comment by richardlau** [comment]
There's already a MAINTAINER.md... should this be renamed to COLLABORATOR_GUIDE.md for consistency with other foundation projects?
