### ISSUE TITLE
Failed at the nodereport@1.0.8 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by ajayit1994** [nodejs/node-report#67]
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-
gyp.js" "rebuild"
gyp ERR! cwd D:\eMenu\eMenuAnalyticsApi\node_modules\nodereport
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN @angular/common@2.4.8 requires a peer of @angular/core@2.4.8 but none was installed.
npm WARN emenuanalyticsapi@1.0.0 No description
npm WARN emenuanalyticsapi@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "noderepor
t"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! nodereport@1.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodereport@1.0.8 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodereport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodereport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodereport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\eMenu\eMenuAnalyticsApi\npm-debug.log

**Comment by bnoordhuis** [comment]
The error is this:

> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

Set the PYTHON environment variable or pass `--python \path\to\python.exe` to npm or node-gyp.  Note that it should be python 2.7, not python 3.x.

**Comment by rnchamberlain** [comment]
Or have python 2.7 on your Windows path.

Note also that nodereport@1.0.8 is obsolete, the project was renamed recently with a hyphen in the name, 'node-report'. The latest version is 2.1.1, see https://www.npmjs.org/package/node-report.

**Comment by rnchamberlain** [comment]
@ajayit1994 did you get past this problem?

There are guidelines for the pre-reqs when installing native npm modules on Windows. See the node-gyp  installation "on Windows" section here: 
https://github.com/nodejs/node-gyp
or the "Compiling native Addon modules" section here:
https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md

**Comment by rnchamberlain** [comment]
Closing as above, thanks

**Comment by ajayit1994** [comment]
thanks
