### ISSUE TITLE
should `nodereport` be npm deprecated?

### ISSUE THREAD

**Issue by sam-github** [nodejs/node-report#68]
See #67 , people may still be using node-report by its old name, perhaps it should be npm deprecated?

See https://docs.npmjs.com/cli/deprecate

**Comment by rnchamberlain** [comment]
I did the npm deprecate thing on node-report already, see https://github.com/nodejs/node-report/issues/35

```
C:\test>npm install nodereport
npm WARN deprecated nodereport@1.0.8: Please upgrade to npmjs.org/node-report
```

Perhaps they don't get that warning when the install fails, or maybe the message just flew past :-(
