### ISSUE TITLE
test/test-fatal-error.js failing on AIX

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-report#69]
It looks like there is a failing test for AIX on node-report

https://ci.nodejs.org/view/post-mortem/job/nodereport-continuous-integration/MACHINE=aix61-ppc64/116/console
```
# Subtest: test/test-fatal-error.js
    1..0
not ok 9 - test/test-fatal-error.js # time=30019.481ms
```

**Comment by rnchamberlain** [comment]
Test passes if I increase the timeout. The default tap test timeout is 30 secs, it passes in approx 120 secs.
https://ci.nodejs.org/job/nodereport-continuous-integration/122/MACHINE=aix61-ppc64/console

The test fills up the heap to cause the fatal OOM error, with --max-old-space-size=20 set to limit the heap size.
