### ISSUE TITLE
Reported glibc version is the version compiled against

### ISSUE THREAD

**Issue by richardlau** [nodejs/node-report#74]
The report is using [` __GLIBC__` and ` __GLIBC_MINOR__`](https://github.com/nodejs/node-report/blob/v2.1.1/src/node_report.cc#L713-L718) which are compile time constants. Should this be the version of the runtime libc.so (see example below)? Should the report include both?

e.g.
```
$ node -p "require('.').getReport()"
================================================================================
==== Node Report ===============================================================

Event: JavaScript API, location: "GetReport"
Dump event time:  2017/03/08 12:43:34
Module load time: 2017/03/08 12:43:34
Process ID: 9150
Command line: node -p require('.').getReport()

Node.js version: v4.8.0
(ares: 1.10.1-DEV, http_parser: 2.7.0, icu: 56.1, modules: 46, openssl: 1.0.2k,
 uv: 1.9.1, v8: 4.5.103.45, zlib: 1.2.8)

node-report version: 2.1.1 (built against Node.js v4.8.0)

OS version: Linux 3.13.0-98-generic #145-Ubuntu SMP Sat Oct 8 20:13:07 UTC 2016
(glibc: 2.17)

Machine: duv-aurora x86_64

================================================================================
==== JavaScript Stack Trace ====================================================

.... etc etc etc

Loaded libraries
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/librt.so.1
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libgcc_s.so.1
  /lib/x86_64-linux-gnu/libpthread.so.0
  /lib/x86_64-linux-gnu/libc.so.6
  /lib64/ld-linux-x86-64.so.2
  /home/users/riclau/sandbox/github/nodereport/api.node

================================================================================


$  /lib/x86_64-linux-gnu/libc.so.6
GNU C Library (Ubuntu EGLIBC 2.19-0ubuntu6.9) stable release version 2.19, by Roland McGrath et al.
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.8.4.
Compiled on a Linux 3.13.11 system on 2016-05-26.
Available extensions:
        crypt add-on version 2.1 by Michael Glad and others
        GNU Libidn by Simon Josefsson
        Native POSIX Threads Library by Ulrich Drepper et al
        BIND-8.2.3-T5B
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<https://bugs.launchpad.net/ubuntu/+source/eglibc/+bugs>.
$ 
```

**Comment by rnchamberlain** [comment]
So in your case, node-report was built against glibc 2.17, and you were running on glibc 2.19.

Yes, we should move the compile time glibc info into the "build against.." line, and also print the runtime level of glibc, if we can get it easily. 

I chopped the report output, for readability

**Comment by richardlau** [comment]
Okay, I'll put a PR together. The runtime level can be obtained via [`gnu_get_libc_version()`](http://man7.org/linux/man-pages/man3/gnu_get_libc_version.3.html).

I reedited the report output to put back the "Loaded libraries" to show that the libc.so.6 in the report and executed in the shell matched. I'll most likely use this (being able to execute libc.so.6) to extend the testcases.

**Comment by bnoordhuis** [comment]
You should look up gnu_get_libc_version() with dlsym() or declare it as a weak symbol, otherwise people are going to get link errors when they use a libc like musl.

**Comment by richardlau** [comment]
@bnoordhuis The current code is in a [`#if defined(__GLIBC__)`](https://github.com/nodejs/node-report/blob/v2.1.1/src/node_report.cc#L713-L715) block -- Is this a sufficient guard for other libc implementations?

**Comment by mhdawson** [comment]
I'm definitely +1 for reporting both the compiled against and runtime versions.

**Comment by bnoordhuis** [comment]
@richardlau You won't be able to build the module on a glibc system, copy it to a musl system and have it work.  If that's an acceptable restriction, an #ifdef guard is fine.

(In fairness, unless you take active steps, you end up with references to symbols like `memcpy@GLIBC_2.xx` in the shared object anyway.)

**Comment by rnchamberlain** [comment]
At some point maybe we'll need to build against and run on musl, or llvm/clang libraries(?), but I'm sure there will be other issues with those. For now I think the #ifdef guard is enough.

**Comment by mhdawson** [comment]
I'm guessing building node on a glibc system and copying it to a musl system does not work today.  If that's correct then I'm thinking the guard is ok.

**Comment by rnchamberlain** [comment]
Fix in https://github.com/nodejs/node-report/pull/76 landed as https://github.com/nodejs/node-report/commit/d44c1c7adb3d2c608c9bbb24a3088eabdfcc1367
