### ISSUE TITLE
can something useful be reported about unhandled rejections?

### ISSUE THREAD

**Issue by sam-github** [nodejs/node-report#75]
https://nodejs.org/api/process.html#process_event_unhandledrejection and the mention of a "PromiseHook C++ API" (https://github.com/nodejs/node/pull/11752) sparked my curiousity, its an interesting thing to know about an applications state.

**Comment by Fishrock123** [comment]
What kind of thing are you hoping for?

**Comment by Fishrock123** [comment]
Something like "these rejections happened before the crash" or something?

**Comment by Fishrock123** [comment]
ping @sam-github

**Comment by sam-github** [comment]
I was thinking specifically of the list of all promises that are currently rejected but do not have error handlers attached. Basically what the `unhandledRejection` event emits. However, it emits it after one "turn of the event loop" (an ill defined concept). Those promises may get an error handler attached sometime later... or may not, and their presence at time of node report may be interesting, if we know something about them that is reportable.

**Comment by Fishrock123** [comment]
Hmmm, so I think this means hooking into `v8::Isolate::SetPromiseRejectCallback()` but that also then means we hijack core's handler...

So we might either have to add a c++ node api for that, or polyfill the node behavior from here...

Also, on shutdown we'd need to synchronously extract the "reason" data. Not too terribly difficult with the debug api, but very hacky and, well, the V8 people are not a fan of people using it.
