### ISSUE TITLE
node-report not building on Windows due to mktime error

### ISSUE THREAD

**Issue by hhellyer** [nodejs/node-report#83]
I ran a build to test some changes (build 153) and saw compile failures on Windows.

They didn't appear related to my changes so I ran a build using master and Node v6 and saw the same failures:
https://ci.nodejs.org/view/post-mortem/job/nodereport-continuous-integration/154/

(smartos also had failures but they were issues running node not compile failures and I will investigate those separately.)

**Comment by hhellyer** [comment]
I've raised PR #85 to resolve this.

**Comment by rnchamberlain** [comment]
Fix landed as https://github.com/nodejs/node-report/commit/1b62e311c879e83bc8c5c8edaad192fb39b9a098

**Comment by rnchamberlain** [comment]
CI now passing OK on Windows
