### ISSUE TITLE
Cannot find module ./api

### ISSUE THREAD

**Issue by dbraynard** [nodejs/node-report#91]
When I run this with from a gulp script I get the error 

> Cannot find module ./api

gulp version: 3.9.1
node version: 6.2.10
This is the line that causes the error.

`const api = require('./api');`

Where is ./api supposed to come from?

**Comment by rnchamberlain** [comment]
See the node-report binding.gyp file, https://github.com/nodejs/node-report/blob/master/binding.gyp 

The 'api' target in the binding.gyp file builds the native component of the node-report module. So when the package is installed it creates the `node_modules/node-report/api.node` binary. Don't know why that does not work with gulp though.

**Comment by dbraynard** [comment]
Turns out that I didn't have the build tools or run them installed on Windows.

**Comment by brahmscode** [comment]
Facing the issue. api.node file not  gettign generated through npm install. Can someone help?

**Comment by brahmscode** [comment]
Facing the saeme issue. api.node file not  getting generated through npm install. Can someone help?
