### ISSUE TITLE
PrintResourceUsage is unimplemented on Windows

### ISSUE THREAD

**Issue by hhellyer** [nodejs/node-report#99]
node-report on Windows does currently obtain process or thread CPU times on Windows, the `PrintResourceUsage` function is unimplemented.

Most of the data could be gathered via these API's:
`GetProcessTimes ` - https://msdn.microsoft.com/en-us/library/ms683223(VS.85).aspx
`GetThreadTimes` - https://msdn.microsoft.com/en-us/library/ms683237(VS.85).aspx

(I can't work on this myself as I don't have a Windows box. I'm not sure how high a priority Windows support for this data is.)

**Comment by richardlau** [comment]
We can port https://github.com/nodejs/node/pull/26406 across.
